# Generated by Django 2.2.28 on 2023-03-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_feedback', '0005_course_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='picture',
            field=models.ImageField(height_field='400', null=True, upload_to='media', width_field='400'),
        ),
    ]
