# Generated by Django 2.2.28 on 2023-03-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_feedback', '0008_auto_20230301_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='picture',
            field=models.ImageField(null=True, upload_to='course_images'),
        ),
    ]
