# Generated by Django 2.2.28 on 2023-03-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_feedback', '0009_auto_20230308_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default='CS1P', unique=True),
            preserve_default=False,
        ),
    ]
